### ISSUE TITLE
Crear Product Backlog

### ISSUE THREAD

**Issue by rcabreu** [briandiaz/OpenCRM#2]
Crear Product Backlog. Escribirlo en la Wiki.

**Comment by rcabreu** [comment]
¿Qué sucede?
Necesitamos el product backlog chicos..
Ánimo Ánimo Ánimo..

**Comment by briandiaz** [comment]
Loooool.
We are working on it.

**Comment by rcabreu** [comment]
I expect it by tomorrow. 
I will also be needing the length you have fixed to your sprint cycles. 
Thanks guys.

**Comment by freddy-mesa** [comment]
The Product Backlog have been posted in the wiki page.
You can review it.
