### ISSUE TITLE
Option to add a variable number of customers to a campaign

### ISSUE THREAD

**Issue by rcabreu** [briandiaz/OpenCRM#25]
As a user, I want to add a variable number of customers to a campaign so that I can target specific populations.

**Comment by rcabreu** [comment]
Guys, please give me a heads-up on this issue. Please do the same for issues #26 , #27 and #28 (but not here, kindly do it on their respective comment threads).

**Comment by rcabreu** [comment]
Four days ago I wrote the comment above, and have not gotten any response. 
I see @briandiaz is the engineer responsible for this issue. 
Brian, any heads up you want to share?

**Comment by briandiaz** [comment]
Sir this issue is in proccess

**Comment by rcabreu** [comment]
Thanks @briandiaz. Please comment ASAP when this issue is expected to be
ready.

On Mon, Dec 9, 2013 at 4:22 PM, Brian Díaz notifications@github.com wrote:

> Sir this issue is in proccess
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/briandiaz/OpenCRM/issues/25#issuecomment-30169555
> .

## 

Muy atentamente,
Roberto Abreu
_Sapere aude!_

**Comment by briandiaz** [comment]
Yes i will.
Thanks

**Comment by briandiaz** [comment]
Sir when you reffer to different populations how you want to target that kind of population?
