### ISSUE TITLE
Configuraciones del Profile

### ISSUE THREAD

**Issue by freddy-mesa** [briandiaz/OpenCRM#3]
Se necesita que para el Sábado que esté listo: 
- Que cuando un usuario se logea, éste obtenga todas las configuraciones pertinentes al profile que el mismo tenga, esto lo harás con  @freddy-mesa.
- Estas configuraciones deben cargarse a todas las vistas del OpenCRM. Esta parte debe integrarse @briandiaz, @joseReyes28 y @YandriPuello

**Comment by YandriPuello** [comment]
Issue completed.
