### ISSUE TITLE
Crear Vistas: HomeView y SettingsView

### ISSUE THREAD

**Issue by freddy-mesa** [briandiaz/OpenCRM#6]
Adicional a esto con @joseReyes28 estaras haciendo el Controller y Model del HomeView y del SettingsView.

HomeView:
- Se tomara como idea el start up de Windows 8
- Al iniciarlo pareceran titles con los nombres de los objetos que un usuario puede ver, esto se realiza con las configuraciones de permisos que el mismo tiene en el sistema.

SettingView:
- En esta vista se incluirá las modificaciones que los permisos que tiene cada usuario.
- El registro de un Usuario
- Se tomará en cuenta los permisos (profile) que cada usuario tenga para accionar los acapites anteriores

**Comment by briandiaz** [comment]
HomeView Completado

**Comment by briandiaz** [comment]
SettingsView Completado
Falta manejo de data
