### ISSUE TITLE
Campaign Module

### ISSUE THREAD

**Issue by freddy-mesa** [briandiaz/OpenCRM#8]
Se tiene que proporcionar un:
- CampaignView
- CampaignController
- CampaignModel

Debe tener los siguientes features:
- Se debe permitir crear nuevas Campaigns.
- Se debe proporcionar una forma en la que se pueda revisar el estado de las Campaigns.
- Se debe permitir añadir Leads.

**Comment by rcabreu** [comment]
What does Compaign mean?

**Comment by briandiaz** [comment]
A Campaign is where the user defines the type of market that fits the budget and establish the expected revenue in a certain date, in fact keep a track of all the type of activities the user does and to measure incomes or numbers of it.

**Comment by briandiaz** [comment]
#### In proccess
